<a href="https://colab.research.google.com/github/vaishnavi-gujare/NumPy-Assignment/blob/main/14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Q1. Array Properties
import numpy as np
arr = np.random.randint(10, 101, size = (5, 6))
print("Array:", arr)
print("Shape:", arr.shape)
print("Size:", arr.size)
print("Data type:", arr.dtype)

Array: [[ 87  40  49  72  43  98]
 [ 46  46  79  74  48  99]
 [ 21 100  65  99  96  56]
 [ 59  92  94  31  70  56]
 [ 19  45  14  17  86  45]]
Shape: (5, 6)
Size: 30
Data type: int64


In [ ]:
# Q2. Statistical Methods - Basic
import numpy as np
arr = np.random.randint(1, 50, 20)
print("Array:", arr)
print("Minimum Value:", arr.min())
print("Index of minimum value:", arr.argmin())
print("Maximum Value:", arr.max())
print("Index of maximum value:", arr.argmax())
print("Sum of elements:", arr.sum())
print("Mean:", arr.mean())
print("Standard Deviation:", arr.std())

Array: [13 19 12  8 34 28 10 30 47 13 43 32 17  7 43  9 38 45 10  1]
Minimum Value: 1
Index of minimum value: 19
Maximum Value: 47
Index of maximum value: 8
Sum of elements: 459
Mean: 22.95
Standard Deviation: 14.548109842862749


In [1]:
# Q3. Statistical Methods on 2D Array
import numpy as np
arr = np.random.randint(20, 80, size=(4, 5))
print("Minimum value:", arr.min())
print("Maximum value:", arr.max())
print("Sum of all elements:", arr.sum())
print("Mean:", arr.mean())
print("Standard Deviation:", arr.std())
print("Sum of each row", arr.sum(axis=1))
print("Sum of each column:", arr.sum(axis=0))

Minimum value: 29
Maximum value: 69
Sum of all elements: 989
Mean: 49.45
Standard Deviation: 12.714067012565256
Sum of each row [252 242 223 272]
Sum of each column: [203 152 223 219 192]


In [6]:
# Q4. Reshape
import numpy as np
arr = np.arange(1, 25)
print("Original array:", arr)
rs = arr.reshape(4, 6)
print("reshape array:", rs)
rs2 = arr.reshape(3, 8)
print("reshape array:", rs2)
rs3 = arr.reshape(2, 3, 4)
print("reshaped arrays:", rs3)

Original array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
reshape array: [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
reshape array: [[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]]
reshaped arrays: [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [7]:
# Q5. NumPy Indexing - 1D & 2D
arr = np.array([[10, 20, 30, 40],
              [50, 60, 70, 80],
              [90, 100, 110, 120]])
print("Orginal array:", arr)
print("First row:", arr[0])
print("Last column:", arr[-1])
print("Submatrix:", arr[0:2, 1:3])
print("All even numbers:",arr[arr % 2 == 0])

Orginal array: [[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]
First row: [10 20 30 40]
Last column: [ 90 100 110 120]
Submatrix: [[20 30]
 [60 70]]
All even numbers: [ 10  20  30  40  50  60  70  80  90 100 110 120]


In [10]:
# Q6. Advanced Indexing
import numpy as np
arr = np.random.randint(1, 101, size=(5, 5))
print("Original array:", arr)
print("Diagonal elements:", np.diag(arr))
print("Elements Greater Than 50:", arr[arr > 50])
arr[arr < 30] = 0
print("Modified Array:", arr)

Original array: [[42 85 81 24 71]
 [81 48 42 37 27]
 [77 44 75 44 62]
 [22 35 77  5 11]
 [64 36 84 11 15]]
Diagonal elements: [42 48 75  5 15]
Elements Greater Than 50: [85 81 71 81 77 75 62 77 64 84]
Modified Array: [[42 85 81  0 71]
 [81 48 42 37  0]
 [77 44 75 44 62]
 [ 0 35 77  0  0]
 [64 36 84  0  0]]


In [11]:
# Q7. Arithmetic Operations
a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])
print("Addition:", a + b)
print("Substraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)
print("Element-wise power:", a ** b)
print("Modulo:", a % b)

Addition: [11 22 33 44]
Substraction: [ 9 18 27 36]
Multiplication: [ 10  40  90 160]
Division: [10. 10. 10. 10.]
Element-wise power: [     10     400   27000 2560000]
Modulo: [0 0 0 0]


In [14]:
# Q8. Matrix Multiplication
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array ([[9,8,7],[6,5,4],[3,2,1]])
print("Element wise multiplication:", A * B)
print("Matrix Multiplication:", (np.dot(A, B)))

Element wise multiplication: [[ 9 16 21]
 [24 25 24]
 [21 16  9]]
Matrix Multiplication: [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [18]:
# Q9. Combined - Properties + Operations + Indexing

import numpy as np
arr = np.random.randn(6, 6)
print("Original Matrix:", arr)
print("shape:", arr.shape)
print("Size:", arr.size)
print("Data Type:", arr.dtype)
print("Index of Maximum Value:", arr.argmax())
print("Index of Minimum Value:", arr.argmin())
print("Top-left 3 x 3 submatrix:", arr[:3, :3])
print("Modified matrix:", arr)
print("Mean of Modified matrix:", arr.mean())

Original Matrix: [[ 0.69399924  1.87658388  0.67431958  0.02062282 -0.79935422 -0.83383837]
 [ 0.47600993  0.84798274 -0.68857924 -1.57014258 -0.91364953  1.10374658]
 [-1.07525821 -0.57085689  0.08378558 -0.26576255 -1.73196621 -0.29679061]
 [-1.0855783  -0.19394089 -1.69885364 -0.3441182  -2.18609449  1.07862503]
 [ 0.16059445  0.13062712 -0.47597454 -1.24228384  0.77984251 -0.60044972]
 [-0.2334666   0.54462637  0.5289768  -0.3387402   0.96384985 -0.84892065]]
shape: (6, 6)
Size: 36
Data Type: float64
Index of Maximum Value: 1
Index of Minimum Value: 22
Top-left 3 x 3 submatrix: [[ 0.69399924  1.87658388  0.67431958]
 [ 0.47600993  0.84798274 -0.68857924]
 [-1.07525821 -0.57085689  0.08378558]]
Modified matrix: [[ 0.69399924  1.87658388  0.67431958  0.02062282 -0.79935422 -0.83383837]
 [ 0.47600993  0.84798274 -0.68857924 -1.57014258 -0.91364953  1.10374658]
 [-1.07525821 -0.57085689  0.08378558 -0.26576255 -1.73196621 -0.29679061]
 [-1.0855783  -0.19394089 -1.69885364 -0.3441182  -

In [19]:
# Q10. Mini Project - Student Performance Analysis

import numpy as np
# 10 student and 5 subject with marks between 30 and 100
marks = np.random.randint(30, 101, size=(10, 5))
print("Student Marks Matrix:", marks)
# calculate total marks for each student
total_marks = marks.sum(axis=1)
print("Total marks of each student:", total_marks)
# calculate average marks of each student
average_marks = marks.mean(axis=1)
print("Average marks of each student:", average_marks)
# student with highest score marks
highest_student = total_marks.argmax()
print("Student with Highest Total Marks:")
print("Student Index:", highest_student)
print("Total Marks:", total_marks[highest_student])
# student with lowest score marks
lowest_student = total_marks.argmin()
print("Student with Lowest Total Marks:")
print("Student Index:", lowest_student)
print("Total Marks:", total_marks[lowest_student])
# calculate class mean
class_mean = marks.mean()
print("Overall Class Mean:")
print(class_mean)
# calculate class standaed deviation
class_std = marks.std()
print("Overall Class Standard Deviation:")
print(class_std)
# Sort students based on total marks
# Get indices of students in ascending order
sorted_indices = np.argsort(total_marks)
top3_indices = sorted_indices[-3:]
print("Top 3 Student Indices:")
print(top3_indices)
# Extract marks of top 3 students using indexing
top3_marks = marks[top3_indices]
print("\nMarks of Top 3 Students:")
print(top3_marks)
# Demonstrate reshape operation
reshaped_marks = marks.reshape(5, 10)
print("Reshaped Array (5 x 10):")
print(reshaped_marks)

Student Marks Matrix: [[ 81  90  72  53  51]
 [ 32  45  84  63  79]
 [ 52  74  78  49  63]
 [ 46  84  60  35  75]
 [ 98  90  92  30  93]
 [ 94  94  39  69  60]
 [ 33  76  50  59  82]
 [ 78  58  40  40  33]
 [ 67  43  99 100  31]
 [ 48  49  62  57  99]]
Total marks of each student: [347 303 316 300 403 356 300 249 340 315]
Average marks of each student: [69.4 60.6 63.2 60.  80.6 71.2 60.  49.8 68.  63. ]
Student with Highest Total Marks:
Student Index: 4
Total Marks: 403
Student with Lowest Total Marks:
Student Index: 7
Total Marks: 249
Overall Class Mean:
64.58
Overall Class Standard Deviation:
21.248143448310962
Top 3 Student Indices:
[0 5 4]

Marks of Top 3 Students:
[[81 90 72 53 51]
 [94 94 39 69 60]
 [98 90 92 30 93]]
Reshaped Array (5 x 10):
[[ 81  90  72  53  51  32  45  84  63  79]
 [ 52  74  78  49  63  46  84  60  35  75]
 [ 98  90  92  30  93  94  94  39  69  60]
 [ 33  76  50  59  82  78  58  40  40  33]
 [ 67  43  99 100  31  48  49  62  57  99]]
